apiVersion: v1
kind: Service
metadata:
  name: saddah-api
  namespace: saddah
  labels:
    app: saddah-api
    component: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: saddah-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: saddah-api
  namespace: saddah
  labels:
    app: saddah-api
